### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by eknoes** [vanhauser-thc/afl-pin#1]
It should be mentioned in the README, that PIN_ROOT must be set to the Path where pin is deployed.
Furthermore, I cannot build it because it cannot find ``pin.H``. Should the gcc flags include the pin-include directory?

**Comment by vanhauser-thc** [comment]
did you set PIN_HOME? that would be the reason why it can not find it.

I just pushed a patch that just uses PIN_ROOT and does not use PIN_HOME and did some minor changes to the makefiles. please retest.

**Comment by eknoes** [comment]
Thanks, it works now!
