### ISSUE TITLE
where is forkserver.so？

### ISSUE THREAD

**Issue by lyliu** [vanhauser-thc/afl-pin#5]
Hi,
I tried to use afl-pin with forkserver, but where is forkserver.so, and i found there is no forkserver.cpp file in pin directory.

**Comment by vanhauser-thc** [comment]
the file is forkserver.c, its in the repository, and when you type "make" it is compiled to forkserver.so

**Comment by lyliu** [comment]
Thanks,
so, you implement forkserver by fork(),instead of using pin's API?

**Comment by vanhauser-thc** [comment]
the forkserver does more than just doing a fork(), it also talks to afl etc. it was the easiest way.
Do you see a disadvantage in that approach? I am open to recommendations.
(also afl-pin is rather an exercise than something useful. if you want to fuzz a blackbox binary then use afl-dyninst or afl -Q qemu mode - or afl-pt if you are willing to work with an old kernel and old ubuntu)

**Comment by lyliu** [comment]
Thanks for your reply!
I just think how to implement forkserver using pin on windows.

**Comment by lyliu** [comment]
Thanks for your reply!
I'm just thinking about how to implement forkserver using pin on windows.
